function daysAgo(n) {
  const d = new Date()
  d.setDate(d.getDate() - n)
  return d.toISOString()
}

export const MOCK_ACHIEVEMENTS = [
  {
    id: 1, user_id: 'demo', github_repo: 'facebook/react',
    github_repo_url: 'https://github.com/facebook/react',
    name: 'Fix memory leak in request handler',
    description: 'Identified and fixed a memory leak in the useEffect cleanup path.',
    url: 'https://github.com/facebook/react/pull/28001',
    github_pr_url: 'https://github.com/facebook/react/pull/28001',
    github_pr_number: 28001,
    issue_url: 'https://github.com/facebook/react/issues/27998',
    issue_title: 'Memory leak when component unmounts rapidly',
    issue_number: 27998,
    status: 'merged',
    started_at: daysAgo(60), submitted_at: daysAgo(58), merged_at: daysAgo(57), closed_at: null,
    created_at: daysAgo(60),
  },
  {
    id: 2, user_id: 'demo', github_repo: 'vercel/next.js',
    github_repo_url: 'https://github.com/vercel/next.js',
    name: 'Add dark mode support to docs',
    description: 'Added CSS variables and a toggle for dark mode across the documentation site.',
    url: 'https://github.com/vercel/next.js/pull/61234',
    github_pr_url: 'https://github.com/vercel/next.js/pull/61234',
    github_pr_number: 61234,
    issue_url: 'https://github.com/vercel/next.js/issues/61100',
    issue_title: 'Docs site does not support dark mode',
    issue_number: 61100,
    status: 'submitted',
    started_at: daysAgo(45), submitted_at: daysAgo(43), merged_at: null, closed_at: null,
    created_at: daysAgo(45),
  },
  {
    id: 3, user_id: 'demo', github_repo: 'vitejs/vite',
    github_repo_url: 'https://github.com/vitejs/vite',
    name: 'Improve error messages for invalid config',
    description: 'Replaced cryptic config validation errors with human-readable messages and links to docs.',
    url: 'https://github.com/vitejs/vite/pull/15321',
    github_pr_url: 'https://github.com/vitejs/vite/pull/15321',
    github_pr_number: 15321,
    issue_url: 'https://github.com/vitejs/vite/issues/15300',
    issue_title: 'Config errors are hard to debug',
    issue_number: 15300,
    status: 'merged',
    started_at: daysAgo(30), submitted_at: daysAgo(28), merged_at: daysAgo(27), closed_at: null,
    created_at: daysAgo(30),
  },
  {
    id: 4, user_id: 'demo', github_repo: 'expressjs/express',
    github_repo_url: 'https://github.com/expressjs/express',
    name: 'Add TypeScript types to plugin API',
    description: 'Working on adding full TypeScript definitions to the plugin middleware API.',
    url: null, github_pr_url: null, github_pr_number: null,
    issue_url: 'https://github.com/expressjs/express/issues/5432',
    issue_title: 'Missing TypeScript types for middleware plugins',
    issue_number: 5432,
    status: 'started',
    started_at: daysAgo(14), submitted_at: null, merged_at: null, closed_at: null,
    created_at: daysAgo(14),
  },
  {
    id: 5, user_id: 'demo', github_repo: 'tailwindlabs/tailwindcss',
    github_repo_url: 'https://github.com/tailwindlabs/tailwindcss',
    name: 'Refactor pagination component',
    description: 'Refactored the pagination component to use CSS grid instead of flexbox hacks.',
    url: 'https://github.com/tailwindlabs/tailwindcss/pull/13210',
    github_pr_url: 'https://github.com/tailwindlabs/tailwindcss/pull/13210',
    github_pr_number: 13210,
    issue_url: 'https://github.com/tailwindlabs/tailwindcss/issues/13190',
    issue_title: 'Pagination layout breaks on small screens',
    issue_number: 13190,
    status: 'closed',
    started_at: daysAgo(10), submitted_at: daysAgo(8), merged_at: null, closed_at: daysAgo(7),
    created_at: daysAgo(10),
  },
  {
    id: 6, user_id: 'demo', github_repo: 'microsoft/vscode',
    github_repo_url: 'https://github.com/microsoft/vscode',
    name: 'Fix keybinding conflict on macOS',
    description: 'Resolved a keybinding conflict between the terminal and editor on macOS.',
    url: 'https://github.com/microsoft/vscode/pull/204111',
    github_pr_url: 'https://github.com/microsoft/vscode/pull/204111',
    github_pr_number: 204111,
    issue_url: 'https://github.com/microsoft/vscode/issues/204000',
    issue_title: 'Keybinding conflict on macOS with terminal',
    issue_number: 204000,
    status: 'merged',
    started_at: daysAgo(5), submitted_at: daysAgo(3), merged_at: daysAgo(2), closed_at: null,
    created_at: daysAgo(5),
  },
  {
    id: 7, user_id: 'demo', github_repo: 'vuejs/vue',
    github_repo_url: 'https://github.com/vuejs/vue',
    name: 'Update composables documentation',
    description: 'Rewrote the composables section with clearer examples and TypeScript annotations.',
    url: 'https://github.com/vuejs/vue/pull/13002',
    github_pr_url: 'https://github.com/vuejs/vue/pull/13002',
    github_pr_number: 13002,
    issue_url: 'https://github.com/vuejs/vue/issues/12990',
    issue_title: 'Composables docs lack TypeScript examples',
    issue_number: 12990,
    status: 'merged',
    started_at: daysAgo(20), submitted_at: daysAgo(18), merged_at: daysAgo(17), closed_at: null,
    created_at: daysAgo(20),
  },
]

export const MOCK_DASHBOARD = {
  top_n: 50,
  windows: {
    daily: {
      top_repositories: [
        { github_repo: 'facebook/react', contributions: 2 },
        { github_repo: 'vitejs/vite', contributions: 1 },
      ],
      top_users: [
        { username: 'testuser', name: 'Test User', contributions: 3 },
        { username: 'alice', name: 'Alice Chen', contributions: 2 },
        { username: 'bob', name: 'Bob Smith', contributions: 1 },
      ],
    },
    weekly: {
      top_repositories: [
        { github_repo: 'facebook/react', contributions: 5 },
        { github_repo: 'vercel/next.js', contributions: 3 },
        { github_repo: 'vitejs/vite', contributions: 2 },
      ],
      top_users: [
        { username: 'testuser', name: 'Test User', contributions: 7 },
        { username: 'alice', name: 'Alice Chen', contributions: 5 },
        { username: 'bob', name: 'Bob Smith', contributions: 3 },
        { username: 'carol', name: 'Carol Wu', contributions: 2 },
      ],
    },
    monthly: {
      top_repositories: [
        { github_repo: 'facebook/react', contributions: 12 },
        { github_repo: 'vercel/next.js', contributions: 8 },
        { github_repo: 'vitejs/vite', contributions: 6 },
        { github_repo: 'microsoft/vscode', contributions: 4 },
        { github_repo: 'tailwindlabs/tailwindcss', contributions: 3 },
      ],
      top_users: [
        { username: 'testuser', name: 'Test User', contributions: 7 },
        { username: 'alice', name: 'Alice Chen', contributions: 5 },
        { username: 'bob', name: 'Bob Smith', contributions: 4 },
        { username: 'carol', name: 'Carol Wu', contributions: 3 },
        { username: 'dave', name: 'Dave Park', contributions: 2 },
      ],
    },
  },
}
