from contextlib import contextmanager

import psycopg
from psycopg.rows import dict_row

from .config import DB_DSN


DEFAULT_PROJECTS = (
    (
        "https://github.com/hkm67/telegram-ai-bot/",
        "Telegram group bot that captures chat context and answers with an Ollama-first LLM agent, Gemini fallback, tool use, and Docker deployment. Has an open issue ready for agent work.",
    ),
    (
        "https://github.com/hoppscotch/hoppscotch/",
        "Open source API development platform for building, testing, and sharing HTTP, GraphQL, and realtime requests. Active TypeScript/Vue project with hundreds of open issues and good first issue candidates.",
    ),
    (
        "https://github.com/treeverse/lakeFS/",
        "Git-like data version control platform for object storage and data lake workflows. Go and Python ecosystem project with a steady backlog of open issues across SDKs, docs, and integrations.",
    ),
    (
        "https://github.com/directus/directus/",
        "Open source data platform and headless CMS that turns SQL databases into APIs and admin apps. JavaScript/TypeScript project with many open issues across frontend, API, extensions, and docs.",
    ),
    (
        "https://github.com/caddyserver/caddy/",
        "Extensible Go web server with automatic HTTPS. Mature infrastructure project with many open issues suitable for focused bug fixes, docs, tests, and module improvements.",
    ),
    (
        "https://github.com/micronaut-projects/micronaut-core/",
        "JVM framework for building modular microservices and serverless apps. Java project with hundreds of open issues, including curated good first issues and framework enhancements.",
    ),
    (
        "https://github.com/milvus-io/milvus/",
        "Open source vector database built for embedding similarity search and AI applications. Go/Python/C++ project with hundreds of open issues across clients, storage, indexing, and docs.",
    ),
    (
        "https://github.com/strapi/strapi/",
        "Open source headless CMS for building customizable content APIs. JavaScript/TypeScript project with a large issue queue across admin UI, plugins, REST/GraphQL APIs, and documentation.",
    ),
    (
        "https://github.com/meilisearch/meilisearch/",
        "Fast open source search engine focused on relevance and developer experience. Rust project with active issues around search behavior, API ergonomics, integrations, and docs.",
    ),
    (
        "https://github.com/novuhq/novu/",
        "Open source notification infrastructure for product teams. TypeScript project with active issues across workflow orchestration, providers, dashboard UX, and SDKs.",
    ),
    (
        "https://github.com/apache/superset/",
        "Apache Superset is a modern data exploration and visualization platform. Python/TypeScript project with hundreds of open issues across charts, dashboards, SQL Lab, and integrations.",
    ),
)


SCHEMA = """
CREATE TABLE IF NOT EXISTS profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    username TEXT NOT NULL UNIQUE,
    preferences JSONB NOT NULL DEFAULT '{"categories": [], "notes": ""}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url TEXT NOT NULL UNIQUE,
    description TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS activities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    opensource_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    timestamp TIMESTAMPTZ NOT NULL DEFAULT now(),
    url TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS achievements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    project_id BIGINT REFERENCES projects(id) ON DELETE SET NULL,
    name TEXT NOT NULL,
    description TEXT,
    url TEXT,
    issue_url TEXT,
    issue_title TEXT,
    issue_number INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
"""


class DbCursor:
    def __init__(self, cursor, lastrowid=None):
        self._cursor = cursor
        self.lastrowid = lastrowid

    @property
    def rowcount(self):
        return self._cursor.rowcount

    def fetchone(self):
        return self._cursor.fetchone()

    def fetchall(self):
        return self._cursor.fetchall()


class DbConnection:
    def __init__(self, connection):
        self._connection = connection

    def close(self):
        self._connection.close()

    def commit(self):
        self._connection.commit()

    def rollback(self):
        self._connection.rollback()

    def execute(self, query, params=None):
        params = params or ()
        cursor = self._connection.cursor()
        sql = _normalize_sql(query)
        lastrowid = None
        if _should_return_id(sql):
            sql = f"{sql.rstrip().rstrip(';')} RETURNING id"
            cursor.execute(sql, params)
            row = cursor.fetchone()
            lastrowid = row["id"] if row else None
        else:
            cursor.execute(sql, params)
        return DbCursor(cursor, lastrowid)

    def executemany(self, query, params_seq):
        cursor = self._connection.cursor()
        cursor.executemany(_normalize_sql(query), params_seq)
        return DbCursor(cursor)

    def executescript(self, script):
        cursor = self._connection.cursor()
        cursor.execute(script)
        return DbCursor(cursor)

    def __enter__(self):
        return self

    def __exit__(self, exc_type, _exc, _tb):
        if exc_type:
            self.rollback()
        self.close()


def _normalize_sql(query):
    return query.replace("?", "%s")


def _should_return_id(sql):
    normalized = " ".join(sql.lower().split())
    if " returning " in normalized:
        return False
    return normalized.startswith(
        (
            "insert into projects ",
            "insert into activities ",
            "insert into achievements ",
        )
    )


def get_connection():
    if not DB_DSN:
        raise RuntimeError("DB_URL_TEMPLATE and DB_PASSWORD are required. Configure Supabase Postgres before starting the API.")
    try:
        connection = psycopg.connect(DB_DSN, row_factory=dict_row, prepare_threshold=None)
    except psycopg.OperationalError as exc:
        raise RuntimeError(
            "Could not connect to Supabase Postgres. Check DB_URL_TEMPLATE and DB_PASSWORD "
            "in .env. Copy the Supabase Postgres URL template with [YOUR-PASSWORD] intact, "
            "and put the raw password in DB_PASSWORD."
        ) from exc
    return DbConnection(connection)


@contextmanager
def transaction():
    connection = get_connection()
    try:
        yield connection
        connection.commit()
    except Exception:
        connection.rollback()
        raise
    finally:
        connection.close()


def _seed_default_projects(connection):
    connection.executemany(
        """
        INSERT INTO projects (url, description)
        VALUES (?, ?)
        ON CONFLICT(url) DO UPDATE SET
            description = excluded.description
        """,
        DEFAULT_PROJECTS,
    )


def init_db():
    with transaction() as connection:
        connection.executescript(SCHEMA)
        _seed_default_projects(connection)


def row_to_dict(row):
    return dict(row) if row is not None else None
