from contextlib import contextmanager

import psycopg
from psycopg.rows import dict_row

from .config import DB_DSN, LOCAL_AUTH_ENABLED


LOCAL_AUTH_SCHEMA = """
CREATE SCHEMA IF NOT EXISTS auth;

CREATE TABLE IF NOT EXISTS auth.users (
    id UUID PRIMARY KEY,
    email TEXT UNIQUE,
    password_hash TEXT,
    raw_user_meta_data JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
"""


SCHEMA = """
CREATE TABLE IF NOT EXISTS profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    username TEXT NOT NULL UNIQUE,
    preferences JSONB NOT NULL DEFAULT '{"categories": [], "notes": ""}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS activities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    github_repo TEXT NOT NULL,
    type TEXT NOT NULL DEFAULT 'started',
    timestamp TIMESTAMPTZ NOT NULL DEFAULT now(),
    url TEXT,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    CHECK (type IN ('started', 'submitted', 'merged', 'closed', 'synced'))
);

CREATE TABLE IF NOT EXISTS achievements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    github_repo TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    url TEXT,
    github_pr_url TEXT,
    github_pr_number INTEGER,
    issue_url TEXT,
    issue_title TEXT,
    issue_number INTEGER,
    status TEXT NOT NULL DEFAULT 'started',
    started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    submitted_at TIMESTAMPTZ,
    merged_at TIMESTAMPTZ,
    closed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (status IN ('started', 'submitted', 'merged', 'closed'))
);
"""


class DbCursor:
    def __init__(self, cursor, lastrowid=None):
        self._cursor = cursor
        self.lastrowid = lastrowid

    @property
    def rowcount(self):
        return self._cursor.rowcount

    def fetchone(self):
        return self._cursor.fetchone()

    def fetchall(self):
        return self._cursor.fetchall()


class DbConnection:
    def __init__(self, connection):
        self._connection = connection

    def close(self):
        self._connection.close()

    def commit(self):
        self._connection.commit()

    def rollback(self):
        self._connection.rollback()

    def execute(self, query, params=None):
        params = params or ()
        cursor = self._connection.cursor()
        sql = _normalize_sql(query)
        lastrowid = None
        if _should_return_id(sql):
            sql = f"{sql.rstrip().rstrip(';')} RETURNING id"
            cursor.execute(sql, params)
            row = cursor.fetchone()
            lastrowid = row["id"] if row else None
        else:
            cursor.execute(sql, params)
        return DbCursor(cursor, lastrowid)

    def executemany(self, query, params_seq):
        cursor = self._connection.cursor()
        cursor.executemany(_normalize_sql(query), params_seq)
        return DbCursor(cursor)

    def executescript(self, script):
        cursor = self._connection.cursor()
        cursor.execute(script)
        return DbCursor(cursor)

    def __enter__(self):
        return self

    def __exit__(self, exc_type, _exc, _tb):
        if exc_type:
            self.rollback()
        self.close()


def _normalize_sql(query):
    return query.replace("?", "%s")


def _should_return_id(sql):
    normalized = " ".join(sql.lower().split())
    if " returning " in normalized:
        return False
    return normalized.startswith(
        (
            "insert into activities ",
            "insert into achievements ",
        )
    )


def get_connection():
    if not DB_DSN:
        raise RuntimeError("DB_URL_TEMPLATE and DB_PASSWORD are required. Configure Supabase Postgres before starting the API.")
    try:
        connection = psycopg.connect(DB_DSN, row_factory=dict_row, prepare_threshold=None)
    except psycopg.OperationalError as exc:
        raise RuntimeError(
            "Could not connect to Supabase Postgres. Check DB_URL_TEMPLATE and DB_PASSWORD "
            "in .env. Copy the Supabase Postgres URL template with [YOUR-PASSWORD] intact, "
            "and put the raw password in DB_PASSWORD."
        ) from exc
    return DbConnection(connection)


@contextmanager
def transaction():
    connection = get_connection()
    try:
        yield connection
        connection.commit()
    except Exception:
        connection.rollback()
        raise
    finally:
        connection.close()


def init_db():
    with transaction() as connection:
        if LOCAL_AUTH_ENABLED:
            connection.executescript(LOCAL_AUTH_SCHEMA)
        connection.executescript(SCHEMA)


def row_to_dict(row):
    return dict(row) if row is not None else None
