create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null,
  username text not null unique,
  preferences jsonb not null default '{"categories": [], "notes": ""}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.activities (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  github_repo text not null,
  type text not null default 'started',
  timestamp timestamptz not null default now(),
  url text,
  metadata jsonb not null default '{}'::jsonb,
  constraint activities_type_check check (type in ('started', 'submitted', 'merged', 'closed', 'synced'))
);

create table if not exists public.achievements (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  github_repo text not null,
  name text not null,
  description text,
  url text,
  github_pr_url text,
  github_pr_number integer,
  issue_url text,
  issue_title text,
  issue_number integer,
  status text not null default 'started',
  started_at timestamptz not null default now(),
  submitted_at timestamptz,
  merged_at timestamptz,
  closed_at timestamptz,
  created_at timestamptz not null default now(),
  constraint achievements_status_check check (status in ('started', 'submitted', 'merged', 'closed'))
);

create index if not exists achievements_user_created_idx
  on public.achievements (user_id, created_at desc);

create index if not exists achievements_github_repo_idx
  on public.achievements (github_repo);

create index if not exists achievements_status_idx
  on public.achievements (status);

alter table public.profiles enable row level security;
alter table public.activities enable row level security;
alter table public.achievements enable row level security;

create policy "Profiles are readable by authenticated users"
  on public.profiles for select
  to authenticated
  using (true);

create policy "Users can update their own profile"
  on public.profiles for update
  to authenticated
  using (auth.uid() = id)
  with check (auth.uid() = id);

create policy "Achievements are publicly readable"
  on public.achievements for select
  to anon, authenticated
  using (true);
