create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null,
  username text not null unique,
  preferences jsonb not null default '{"categories": [], "notes": ""}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  url text not null unique,
  description text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.activities (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  opensource_id bigint not null references public.projects(id) on delete cascade,
  timestamp timestamptz not null default now(),
  url text not null
);

create table if not exists public.achievements (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  project_id bigint references public.projects(id) on delete set null,
  name text not null,
  description text,
  url text,
  issue_url text,
  issue_title text,
  issue_number integer,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.projects enable row level security;
alter table public.activities enable row level security;
alter table public.achievements enable row level security;

create policy "Profiles are readable by authenticated users"
  on public.profiles for select
  to authenticated
  using (true);

create policy "Users can update their own profile"
  on public.profiles for update
  to authenticated
  using (auth.uid() = id)
  with check (auth.uid() = id);

create policy "Projects are publicly readable"
  on public.projects for select
  to anon, authenticated
  using (true);

create policy "Achievements are publicly readable"
  on public.achievements for select
  to anon, authenticated
  using (true);

insert into public.projects (url, description) values
  ('https://github.com/hkm67/telegram-ai-bot/', 'Telegram group bot that captures chat context and answers with an Ollama-first LLM agent, Gemini fallback, tool use, and Docker deployment. Has an open issue ready for agent work.'),
  ('https://github.com/hoppscotch/hoppscotch/', 'Open source API development platform for building, testing, and sharing HTTP, GraphQL, and realtime requests. Active TypeScript/Vue project with hundreds of open issues and good first issue candidates.'),
  ('https://github.com/treeverse/lakeFS/', 'Git-like data version control platform for object storage and data lake workflows. Go and Python ecosystem project with a steady backlog of open issues across SDKs, docs, and integrations.'),
  ('https://github.com/directus/directus/', 'Open source data platform and headless CMS that turns SQL databases into APIs and admin apps. JavaScript/TypeScript project with many open issues across frontend, API, extensions, and docs.'),
  ('https://github.com/caddyserver/caddy/', 'Extensible Go web server with automatic HTTPS. Mature infrastructure project with many open issues suitable for focused bug fixes, docs, tests, and module improvements.'),
  ('https://github.com/micronaut-projects/micronaut-core/', 'JVM framework for building modular microservices and serverless apps. Java project with hundreds of open issues, including curated good first issues and framework enhancements.'),
  ('https://github.com/milvus-io/milvus/', 'Open source vector database built for embedding similarity search and AI applications. Go/Python/C++ project with hundreds of open issues across clients, storage, indexing, and docs.'),
  ('https://github.com/strapi/strapi/', 'Open source headless CMS for building customizable content APIs. JavaScript/TypeScript project with a large issue queue across admin UI, plugins, REST/GraphQL APIs, and documentation.'),
  ('https://github.com/meilisearch/meilisearch/', 'Fast open source search engine focused on relevance and developer experience. Rust project with active issues around search behavior, API ergonomics, integrations, and docs.'),
  ('https://github.com/novuhq/novu/', 'Open source notification infrastructure for product teams. TypeScript project with active issues across workflow orchestration, providers, dashboard UX, and SDKs.'),
  ('https://github.com/apache/superset/', 'Apache Superset is a modern data exploration and visualization platform. Python/TypeScript project with hundreds of open issues across charts, dashboards, SQL Lab, and integrations.')
on conflict (url) do update set description = excluded.description;
